//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management_System.Areas.Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMSEntities1 : DbContext
    {
        public PMSEntities1()
            : base("name=PMSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Designation> tbl_Designation { get; set; }
        public virtual DbSet<tbl_ManageProjects> tbl_ManageProjects { get; set; }
        public virtual DbSet<tbl_TaskSummary> tbl_TaskSummary { get; set; }
        public virtual DbSet<tbl_TimeSheet> tbl_TimeSheet { get; set; }
        public virtual DbSet<tbl_SuperAdminLogin> tbl_SuperAdminLogin { get; set; }
        public virtual DbSet<tbl_ManageTask> tbl_ManageTask { get; set; }
        public virtual DbSet<tbl_ManageUsers> tbl_ManageUsers { get; set; }
    }
}
