//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management_System.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TimeSheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_TimeSheet()
        {
            this.tbl_TaskSummary = new HashSet<tbl_TaskSummary>();
        }
    
        public int id { get; set; }
        public Nullable<int> FKprojectid { get; set; }
        public Nullable<int> FKtaskid { get; set; }
        public Nullable<int> FKuserid { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<int> actualhours { get; set; }
        public string comments { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    
        public virtual tbl_ManageProjects tbl_ManageProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TaskSummary> tbl_TaskSummary { get; set; }
        public virtual tbl_ManageTask tbl_ManageTask { get; set; }
    }
}
