//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management_System.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_ManageProjects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ManageProjects()
        {
            this.tbl_TimeSheet = new HashSet<tbl_TimeSheet>();
            this.tbl_ManageTask = new HashSet<tbl_ManageTask>();
        }
    
        public int projectid { get; set; }

        [Required]
        public string projectname { get; set; }
        public string description { get; set; }

        [Required]
        public Nullable<System.DateTime> startdate { get; set; }

        [Required]
        public Nullable<System.DateTime> enddate { get; set; }

        [Required]
        public string documentupload { get; set; }

        [Required]
        public Nullable<int> estimatedhours { get; set; }
        public Nullable<int> actualhours { get; set; }
        public string projectstatus { get; set; }
        public Nullable<bool> activitystatus { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TimeSheet> tbl_TimeSheet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ManageTask> tbl_ManageTask { get; set; }
    }
}
