//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management_System.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ManageTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ManageTask()
        {
            this.tbl_TimeSheet = new HashSet<tbl_TimeSheet>();
        }
    
        public int taskid { get; set; }
        public string taskname { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<int> estimatedhours { get; set; }
        public string taskstatus { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<int> FKuserid { get; set; }
        public Nullable<int> FKprojectid { get; set; }
        public Nullable<int> FKdesignationid { get; set; }
        public Nullable<int> TaskCount { get; set; }
    
        public virtual tbl_Designation tbl_Designation { get; set; }
        public virtual tbl_ManageProjects tbl_ManageProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TimeSheet> tbl_TimeSheet { get; set; }
        public virtual tbl_ManageUsers tbl_ManageUsers { get; set; }
    }
}
