//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Management_System.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_SuperAdminLogin
    {
        public int id { get; set; }

        [Required]
        public string useremail { get; set; }

        [Required]
        public string password { get; set; }
        public string ResetPassword { get; set; }
    }
}
